### ISSUE TITLE
Cleanup netquack-api.json

### ISSUE THREAD

**Issue by phretor** [FiorixF1/NetQuack#2]
I guess the `dcati6zcrh` part should be made into a variable.

```
"servers": [
    {
      "url": "https://dcati6zcrh.execute-api.${AWS_REGION}.amazonaws.com/{basePath}",
      "variables": {
        "basePath": {
          "default": "/dev"
        }
      }
```

**Comment by FiorixF1** [comment]
Hi,

The ```netquack-api.json``` is generated by API Gateway when exporting the API definition and it is used by Terraform when importing it. The "URL" property inside the "servers" object is irrilevant, because AWS will generate a new URL when importing the API.

HOWEVER, indeed there are some hard-coded values when exporting the API, such as the user ID, the AWS region, and the names of the Lambda functions. For this reason, the API definition contains some variables such as ```${AWS_REGION}``` and ```${AWS_USER}```. Those variables were inserted by me manually in the file. Now in babee1b I added a script that automatically inserts these variables through a regexp. This way, if in the future the API will be modified with new resources or methods, the new API definition can be easily exported with variables.
